project:
  type: website
  output-dir: docs

editor:
  render-on-save: true

execute:
  freeze: auto

website:
  # title: "Harrison's Website"
  back-to-top-navigation: true
  sidebar:
    - id: japan
      title: 日本行
      style: floating
      contents: 
        - japan/japan.qmd
        - japan/miyazaki2025/miyazaki.qmd
        - japan/tokyo2026/tokyo.qmd
    - id: japan-miyazaki
      title: 宮崎
      style: floating
      contents:
        - japan/japan.qmd
        - section: "宮崎"
          contents: 
            - japan/miyazaki2025/miyazaki.qmd
            - section: "行程"
              contents: 
              - japan/miyazaki2025/星期一.qmd
              - japan/miyazaki2025/星期二.qmd
              - japan/miyazaki2025/星期三.qmd
              - japan/miyazaki2025/星期四.qmd
            - japan/miyazaki2025/景點.qmd
            - japan/miyazaki2025/food.qmd
    - id: japan-tokyo
      title: 東京
      style: floating
      contents:
        - japan/japan.qmd
        - section: "東京"
          contents:
            - japan/tokyo2026/tokyo.qmd
            - section: "行程"
              contents:
                - japan/tokyo2026/tokyo0821.qmd
                - japan/tokyo2026/tokyo0822.qmd
                - japan/tokyo2026/tokyo0823.qmd
                - japan/tokyo2026/tokyo0824.qmd
                - japan/tokyo2026/tokyo0825.qmd
                - japan/tokyo2026/tokyo0826.qmd
                - japan/tokyo2026/tokyo0827.qmd
                - japan/tokyo2026/tokyo0828.qmd
                - japan/tokyo2026/tokyo0829.qmd
                - japan/tokyo2026/tokyo0830.qmd
                - japan/tokyo2026/tokyo0831.qmd
                - japan/tokyo2026/tokyo0901.qmd
                - japan/tokyo2026/tokyo0902.qmd
                - japan/tokyo2026/tokyo0903.qmd
                - japan/tokyo2026/tokyo0904.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
      # - cosmo
      # - brand
    css: styles.css
    toc: true
