---
title: 食之時
format:
    html:
        navbar: false
        sidebar: japan-miyazaki
---
# 食材
## 日本最美味的牛肉「宮崎牛」
宮崎牛是宮崎縣的品牌牛，在每5年舉辦一次的「和牛奧運」，也就是全國和牛能力共進會中，自2007年起連續4屆獲頒內閣總理大臣獎。

而在「美國奧斯卡金像獎」會後派對的官方餐點中也採用宮崎牛，不僅在日本國內，在世界各地也大獲好評。來到宮崎，一定要品嘗看看這道美味。

宮崎牛口感柔嫩、入口即化，不妨享用牛排、烤肉、壽喜燒或涮涮鍋！

## 可享受宮崎本地雞的口感「炭烤本地雞」
說到宮崎的代表美食，就非炭烤本地雞莫屬。用胡椒鹽等調味後，以高溫炭火一口氣將本地雞烤熟，香氣四溢且口感軟嫩為其特色。

炭烤本地雞非常適合搭配宮崎縣產燒酌，可在專賣店或居酒屋享用這道料理。

## 在發祥地延岡享用道地的「南蠻炸雞」
延岡市有兩間「南蠻炸雞」的發祥店。

「Naochan」將雞肉裹上混合麵粉與雞蛋的麵衣後油炸，再以甘醋醃成。

「Ogura」則是最先淋上塔塔醬的店家，這種風格成為標準口味。滿溢而出的肉汁、沾醬及醬汁的酸甜滋味令人欲罷不能。

不妨來品嘗當地的原始美味。

## 面朝廣闊大海的宮崎縣的豐富海鮮
宮崎縣面朝太平洋，擁有悠長的海岸線，可說是海鮮的寶庫！可在當地享用縣內各地的鄉土料理及當地美食，品嘗當季滋味。

- 伊勢龍蝦: 「伊勢龍蝦」的捕撈期於9月開始，秋天時進入最美味的時期。在日南海岸會舉辦伊勢龍蝦的相關活動或市集。歡迎前往享用各店家的自豪料理，品味新鮮的天然伊勢龍蝦。

- 牡蠣: 生長在宮崎縣中部高鍋町周邊岩岸的天然牡蠣，肉雖小但滋味濃郁。此外，宮崎縣北部日豐海岸也是知名的谷灣式海岸，在這裡的近海可捕獲岩牡蠣，大顆且濃郁順口。

- 鰹魚: 日南市自古以來漁業興盛，透過以釣竿釣起一隻隻鰹魚的漁法，達到日本第一的鰹魚捕撈量。歡迎來嘗試宮崎的特色吃法，例如只炙烤魚皮後沾醬油食用的「炙烤鰹魚」、將調味鰹魚炙烤後盛放在白飯上的「炙烤鰹魚漆飯盒」等。

- 鰤魚/紅甘: 宮崎縣的鰤魚與紅甘養殖盛行。清透的魚肉與彈牙口感，帶有適度油脂，深獲縣內外好評。

- 鰻魚: 宮崎產鰻魚皮薄肉嫩，富含油脂，入口即化。當地利用宮崎得天獨厚的環境，致力於養殖鰻魚，產量位居日本第三。在產地宮崎，可以較為實惠的價格享用高品質鰻魚。

- 大眼青眼魚: 大眼青眼魚是清淡的白肉魚，魚骨柔嫩，帶有適度油脂，滋味高雅。可享用油炸、干物、以甜醋辣椒醬汁醃漬炸魚肉的「南蠻漬」等料理。

## 充滿個性的宮崎縣拉麵
宮崎拉麵一般是以清爽的豚骨湯頭、中粗麵條搭配川燙過的豆芽菜。雖然也有店家供應濃郁的豚骨拉麵，但可不能忘了源自宮崎的「辛麵」！放入大蒜、辣椒、絞肉及韭菜，再打入雞蛋的湯頭，讓人欲罷不能！此外，近年來人氣扶搖直上的番茄拉麵也是推薦品嘗的宮崎特色美食。

## 深植於當地的烏龍麵文化
宮崎烏龍麵的特色在於略為柔軟的細麵，尤其是會沾取以醬油為基底的柚子沾醬來食用。在宮崎縣，不僅會將烏龍麵當作正餐，也是喝酒後必吃的美食。有許多店家早上6點就會開始營業，早餐吃烏龍麵的文化也深植人心。

## 沐浴充足太陽光的宮崎特色南國水果
宮崎縣的溫暖氣候與肥沃大地孕育出特產「南國水果」。當地有許多可採水果的景點！

- 成熟芒果: 宮崎的成熟芒果聞名於日本國內，甚至「說到宮崎就會想到芒果」。果皮稍有彈性且散發香氣，當果皮表面出現光澤時，就代表是品嘗的最佳時機！宮崎芒果的特色是入口即化的果肉與濃郁甜味。
其中僅有符合味道、重量、色澤嚴格標準的芒果，才能成為冠名「太陽蛋」的頂級品種。當地對於芒果的「成熟」十分講究，只將成熟後從樹上自然掉落的果實以網袋接住採收。

- 日向夏蜜柑: 日向夏蜜柑是可連皮食用的柑橘，特色在於可如同削蘋果皮一般，剝開薄薄的黃色外皮，連同內部的白皮一起食用。甘甜白皮結合酸味果肉，呈現出高雅清爽的滋味。

- 成熟長壽金柑: 長壽金柑果實小，酸甜且帶有苦味，可連皮生吃。與以往的品種相比，宮崎縣產品牌「成熟長壽金柑　Tamatama」的特色在於既大又甜，令人驚豔。厚實果肉呈現甘甜清爽的滋味。

## 暢飲日本第一的宮崎燒酎
宮崎縣是燒酎出貨量日本第一的燒酎王國！當地擁有釀造燒酎不可或缺的優質天然水，釀出美味高品質的燒酎。此外，由於當地生產各式各樣的農產品，可運用種類豐富的原料釀造燒酎也是其特色。縣內各地共有38間釀酒廠，各家釀酒商以地瓜、小麥或米等原料釀製特色燒酎。酒精濃度的主流為20度，由於也有只在宮崎縣內才能買到的燒酎，可到宮崎試喝比較，也適合買伴手禮送給愛酒的朋友。

## 還有很多！宮崎縣的知名料理
- 萵苣捲壽司: 萵苣捲壽司起源於宮崎市的「壽司店 一平」，在醋飯上鋪放萵苣、蝦子及自製美乃滋，再以海苔捲起。一般認為這是沙拉捲壽司及海外也可看見的壽司捲原型。除了壽司店以外，也有居酒屋、烏龍麵店等眾多店家供應，可享受各店家的口味。

- 冷湯: 冷湯是適合在天氣熱時享用的宮崎鄉土料理。
在白飯淋上碎烤魚肉的冷味噌湯，再加入小黃瓜、紫蘇、豆腐等配料。
每家店的口味及配菜各有不同，歡迎來品嘗各式各樣的冷湯。

- 煎餃: 宮崎市民超喜歡煎餃！不僅市內，縣內所有地區都有專賣店。除了在店家享用之外，買回家煎烤食用的文化也深植於當地。宮崎煎餃依店家不同，也有各式各樣的內餡與外皮。推薦來一趟煎餃店巡禮，享受不同口味的煎餃。


# 餐廳

## 高千穗峽周邊

### [とんかつ峯](https://maps.app.goo.gl/i1o7pJPsYH75pD1Z7)

::: {.callout}
- $11:00 \sim 15:00, 17:00 \sim 20:30$
- $4.0\ \textcolor{orange}{\bigstar} \ (249)$
- 現金、信用卡、行動掃碼支付
- $\yen 1000 \sim \yen 2000$
- 炸豬排
- [menu](https://ramffys.com/tonkatsu/menu/)
:::

### [ともえまる食堂](https://maps.app.goo.gl/fckF3tqgPsHSWomW6)

::: {.callout}
- $11:00 \sim 13:45, 17:00 \sim 19:00$
- $4.4\ \textcolor{orange}{\bigstar} \ (440)$
- $\yen 1000 \sim \yen 2000$
- 定食
- [menu](https://tomoemaru.jp/shokudo/)
:::

### [たぬき](https://maps.app.goo.gl/zEUZ8wT9uBZH3CV78)

::: {.callout}
- $17:30 \sim 03:30$
- $4.4\ \textcolor{orange}{\bigstar} \ (82)$
- $\yen 1000 \sim \yen 2000$
- 定食
- [menu](https://www.google.com/maps/place/Tanuki/@32.7105209,131.3093647,813m/data=!3m1!1e3!4m7!3m6!1s0x35472ced0955d53d:0x4632e9b114ae1f2f!8m2!3d32.7105209!4d131.3093647!10e9!16s%2Fg%2F1tgpkv57?authuser=0&hl=en&entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::


## 青島周邊

#### [tabelog](https://tabelog.com/tw/miyazaki/A4501/A450101/R69/rstLst/?SrtT=rt&railroad=true)

### [漁師の牡蠣小屋](https://maps.app.goo.gl/4sssk1SZEZHDdt7A9)

::: {.callout}
- 海鮮料理店
- $11:00 \sim 21:00$
- $4.3\ \textcolor{orange}{\bigstar} \ (1583)$
- $\yen 3000 \sim \yen 5000$
- 牡蠣限時吃到飽 3,300日圓（含稅）
- 牡蠣跟燒肉限時吃到飽 4,400日圓（含稅）
- [menu](https://www.hotpepper.jp/strJ001201046/course/)
:::

### [漁師料理 ひで丸](https://maps.app.goo.gl/WiD8inDuvvft5JBXA)

::: {.callout}
- 海鮮料理店
- $11:00 \sim 14:00, 17:00 \sim 20:00$
- $4.4\ \textcolor{orange}{\bigstar} \ (513)$
- $\yen 1000 \sim \yen 2000$
- [menu](https://www.google.com/maps/place/Hidemaru/@31.800713,131.4682395,821m/data=!3m1!1e3!4m7!3m6!1s0x3538c64c485c5a1b:0x522210228a794005!8m2!3d31.800713!4d131.4682395!10e9!16s%2Fg%2F1tcvrm1t?authuser=0&hl=en&entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::

### [青島花園食堂](https://maps.app.goo.gl/2KwvXbZ3jtm4LrCSA)

::: {.callout}
- $09:00 \sim 15:00$
- $4.0\ \textcolor{orange}{\bigstar} \ (244)$
- $\yen 1000 \sim \yen 2000$
- [menu](https://www.miyakoh.co.jp/shop/direct/aoshimaya.html#restaurant)
:::

### [漁師の味 港あおしま](https://maps.app.goo.gl/wJKJZb2nDTrtwaX4A)

::: {.callout}
- 海鮮料理店
- $11:00 \sim 14:00$, 週一公休
- $4.2\ \textcolor{orange}{\bigstar} \ (530)$
- $\yen 1000 \sim \yen 2000$
- [menu](https://www.google.com/maps/place/Ryoshi+no+Aji-Minato+Aoshima+-+Fishermen+taste/@31.7952324,131.4712228,821m/data=!3m1!1e3!4m16!1m8!3m7!1s0x3538c64fd6632e09:0x97d942b1523a879!2sRyoshi+no+Aji-Minato+Aoshima+-+Fishermen+taste!8m2!3d31.7952324!4d131.4712228!10e2!16s%2Fg%2F11cktgv57p!3m6!1s0x3538c64fd6632e09:0x97d942b1523a879!8m2!3d31.7952324!4d131.4712228!10e9!16s%2Fg%2F11cktgv57p?entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::


## 䶏戶周邊
找不到 ¯\\\_(ツ)\_/¯


## 飫肥城下町
### [おび天本舗](https://maps.app.goo.gl/Y1DYK4gXX7CQfBYJ6)

::: {.callout}
- 天婦羅
- $08:30 \sim 17:30$
- $3.9\ \textcolor{orange}{\bigstar} \ (131)$
- $\sim \yen 1000$
- [menu](https://www.obiten.co.jp/netshop/obiten)
:::

### [服部亭](https://maps.app.goo.gl/SNbvZpPfRJDJjBfC9)

::: {.callout}
- $11:00 \sim 14:00$
- $4.3\ \textcolor{orange}{\bigstar} \ (160)$
- $\yen 1000 \sim \yen 2000$
- [menu](https://www.google.com/maps/place/Hattoritei/@31.6264494,131.3515466,17z/data=!4m15!1m7!3m6!1s0x3538d42dcd5161ad:0xbdd95ab725acb341!2sObiten+Honpo!8m2!3d31.6270809!4d131.353626!16s%2Fg%2F1tdkpk4z!3m6!1s0x3538d42e84118a4d:0x23d6927dec0d23ad!8m2!3d31.6280521!4d131.3540267!10e9!16s%2Fg%2F1tdbzddp?authuser=0&hl=en&entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::

### [厚焼たまご あらたけ](https://maps.app.goo.gl/yo8z2qB6YnPy6dkW8)

::: {.callout}
- 玉子燒
- $09:30 \sim 16:00$
- $4.1\ \textcolor{orange}{\bigstar} \ (25)$
- [menu](https://www.google.com/maps/place/厚焼たまご+あらたけ/@31.6252341,131.3544076,17z/data=!4m7!3m6!1s0x3538d42c59a1ac37:0xe6fda2029ad43567!8m2!3d31.6252341!4d131.3544076!10e9!16s%2Fg%2F11btl_vdnz?authuser=0&hl=en&entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::

### [ギャラリーこだま](https://maps.app.goo.gl/3ortD5UmcBpoJ9nF9)

::: {.callout}
- 海鮮
- $10:00 \sim 15:00$, 週二公休
- $4.3\ \textcolor{orange}{\bigstar} \ (181)$
- $\yen 1000 \sim \yen 2000$
- [menu](https://www.icchaga.net/aburi/tenpo/kodama.html)
:::

### [お食事処 さき](https://maps.app.goo.gl/4jx13gmMPdCeBE3A7)

::: {.callout}
- 定食
- $11:00 \sim 16:00$, 週一公休
- $4.2\ \textcolor{orange}{\bigstar} \ (88)$
- $\yen 1000 \sim \yen 2000$
- [menu](https://www.google.com/maps/place/お食事処+さき/@31.6260035,131.3507543,17z/data=!4m16!1m8!3m7!1s0x3538d43284995555:0x46037f0d55117eb7!2z44GK6aOf5LqL5YemIOOBleOBjQ!8m2!3d31.6259738!4d131.3507628!10e5!16s%2Fg%2F11f4t7fzf8!3m6!1s0x3538d43284995555:0x46037f0d55117eb7!8m2!3d31.6259738!4d131.3507628!10e9!16s%2Fg%2F11f4t7fzf8?authuser=0&hl=en&entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::


### [おび天 蔵](https://maps.app.goo.gl/sshz5e4nQ7GxqJ3t8)

::: {.callout}
- 郷土料理
- $09:00 \sim 17:00$
- $3.9\ \textcolor{orange}{\bigstar} \ (255)$
- $\yen 1000 \sim \yen 2000$
- [menu](https://www.obiten.co.jp/stores/obitenkura)
:::

### [$\bigstar$ 武家屋敷 伊東邸](https://maps.app.goo.gl/y7oFYUbzn2QmkAXY8)

::: {.callout}
- 郷土料理
- $11:00 \sim 17:00$, 週二公休
- $4.5\ \textcolor{orange}{\bigstar} \ (275)$
- $\yen 1000 \sim \yen 2000$
- [menu](http://www.itotei.com/obisaryo)
:::


## 市區
### [美食街 - 西橘町 Nishitachi](https://maps.app.goo.gl/3QFJ42m5zWjV4YDaA)

### [うなぎ 海雲](https://maps.app.goo.gl/XGZF5Tu2rEFMP9Yf9)

::: {.callout}
- $10:00 \sim 19:00$ 週三公休
- $4.1\ \textcolor{orange}{\bigstar} \ (166)$
- $\yen 2000 \sim \yen 3000$
- 日式居酒屋
- [menu](https://tabelog.com/tw/miyazaki/A4501/A450101/45010885/)
:::

### [大人の隠れ家 ポッロ](https://maps.app.goo.gl/HR6kpp3yYps5JvxD7)

::: {.callout}
- $18:00 \sim 23:00$ 週日公休
- $4.3\ \textcolor{orange}{\bigstar} \ (46)$
- $\yen 2000 \sim \yen 3000$
- 日式居酒屋
- [menu](https://tabelog.com/tw/miyazaki/A4501/A450101/45008157/)
- [instagram](https://www.instagram.com/pollo.miyazaki?igsh=eWZqaXhuY3pscG9l&utm_source=qr)
:::

### [丸万焼鳥本店](https://maps.app.goo.gl/4nvX4yuyHSc7H9Zx6)

::: {.callout}
- $11:00 \sim 22:00$ 週一公休
- $4.2\ \textcolor{orange}{\bigstar} \ (1223)$
- $\yen 2000 \sim \yen 3000$
- 雞肉料理, 烤雞肉串, 日式居酒屋
- [menu](https://tabelog.com/tw/miyazaki/A4501/A450101/45000079/dtlmenu/photo/)
:::

### [水果大野ANNEX](https://maps.app.goo.gl/qrT22MPJpBeNu63B9)

::: {.callout}
- $13:00 \sim 22:00$
- $4.2\ \textcolor{orange}{\bigstar} \ (326)$
- $\yen 1000 \sim \yen 2000$
- 水果甜點店
- [menu](https://www.google.com/maps/place/フルーツ大野+パーラー/@31.9121071,131.4188571,820m/data=!3m1!1e3!4m11!1m2!2m1!1z5rC05p6c5aSn6YeOQU5ORVg!3m7!1s0x3538b76b44bbffff:0x73ebb3e923db5c3d!8m2!3d31.9121071!4d131.4210458!10e9!15sChHmsLTmnpzlpKfph45BTk5FWFoVIhPmsLTmnpwg5aSn6YeOIGFubmV4kgEMZnJ1aXRfcGFybG9y4AEA!16s%2Fg%2F11ddx8q2cm?entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::

### [釜揚烏龍麵 戶隱本店](https://maps.app.goo.gl/k19SQeka1XLPFDaj7)

::: {.callout}
- $19:00 \sim 02:00$
- $4.2\ \textcolor{orange}{\bigstar} \ (1351)$
- $\yen 700 \sim\yen 1000$
- 烏龍麵
- 信用卡不可
- [官網](http://www.miyazaki-togakushi.com)
:::

### [ぐんけい本店 隠蔵](https://maps.app.goo.gl/YfnNcCoZz8xq3rg6A)

::: {.callout}
- $17:00 \sim 24:00$
- $3.8\ \textcolor{orange}{\bigstar} \ (845)$
- 信用卡
- $\yen 3500$
- 鶏料理店 晚餐, 飲料喝到飽
- [menu](https://gurunavi.com/en/faux200/mn/menu1/rst/?__ngt__=TT171398565008ac1e4a5abb5w_7mBnBiUMcUp9J1Y200n)
- [照片](https://r.gnavi.co.jp/faux200/photo/)
:::


### [宮崎料理と串カツ春日](https://maps.app.goo.gl/kVfe2BNVeoRycrkN7)

::: {.callout}
- 店休日：週一
- 週二至週五$17:00 \sim 23:00$
- 週六和周日$14:00 \sim 23:00$
- $4.3\ \textcolor{orange}{\bigstar} \ (204)$
- 信用卡、電子支付、行動掃碼支付
- $\yen 2000 \sim \yen 3000$
- 居酒屋 串炸
- [menu](https://www.hotpepper.jp/strJ001007793/course/)
:::

### [とんかつ峯](https://maps.app.goo.gl/DZowPAm19zcRxESU7)

::: {.callout}
- $11:00 \sim 15:00, 17:00 \sim 21:00$
- $4.0\ \textcolor{orange}{\bigstar} \ (424)$
- 現金、信用卡、行動掃碼支付
- $\yen 1000 \sim \yen 2000$
- 炸豬排
- [menu](https://ramffys.com/tonkatsu/menu/)
:::

### [Butaman ぶたまん](https://maps.app.goo.gl/ZinEmzorNeBJRqHZ6)

::: {.callout}
- $12:00 \sim 15:00, 18:00 \sim 21:00$ (最後點餐時間20:40)
- 店休日：星期二
- $3.8\ \textcolor{orange}{\bigstar} \ (89)$
- 接受現金和行動掃碼支付
- $\yen 1000 \sim \yen 2000$
- 拉麵
- [menu](https://www.google.com/maps/place/Butaman/@31.9141628,131.419195,721m/data=!3m1!1e3!4m7!3m6!1s0x3538b71b80518e8f:0xc36ad91a2330a4c1!8m2!3d31.9141628!4d131.4217753!10e9!16s%2Fg%2F11gwg1fdp6?entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::

### [おいしい亭](https://maps.app.goo.gl/ywpjPp57N2AcEJr16)

::: {.callout}
- $11:30 \sim 14:00, 17:30 \sim 20:00$
- 店休日：星期二
- $4.5\ \textcolor{orange}{\bigstar} \ (68)$
- $\yen 1000 \sim \yen 2000$
- 僅接受現金支付
- 日式定食 食堂
- [menu](https://www.google.com/maps/place/おいしい亭/@31.9149953,131.4211432,17z/data=!4m7!3m6!1s0x3538b764eea8c139:0x1a641a073fda6f10!8m2!3d31.9149953!4d131.4237235!10e9!16s%2Fg%2F11fm54y3nt?entry=ttu&g_ep=EgoyMDI1MTEwMi4wIKXMDSoASAFQAw%3D%3D)
:::

### [辛麺屋 桝元 宮崎本店](https://maps.app.goo.gl/vyW6hWDemE13zTBs9)

::: {.callout}
- $11:00 \sim 22:00$
- $3.8\ \textcolor{orange}{\bigstar} \ (681)$
- $\yen 1000 \sim \yen 2000$
- [menu](https://www.karamenya-masumoto.com/menu/)

第一站來到了宮崎縣在地人都知道的「辛麵 桝元」！看到「辛麵」這個名字，可能會讓許多不敢吃辣的朋友退避三舍，但其實不需要擔心，因為在點餐的時候可選擇辣度，等級從0到30，大家可以視個人喜好調整。若選擇番茄口味的辛麵，其番茄湯底的甜味會稍微中和掉唐辛子的辣度，那有點辣卻令人忍不住一口接一口的好滋味深受男女老少喜愛，也很推薦加點起司一起享用。一般來說，想稍微嚐嚐辛麵味道的朋友，在辣度的部分可以選擇3或5。此外，除了招牌辛麵之外，「辛麵 桝元」也有提供由豆乳和塩麴熬製的白色辛麵及咖哩麵喔！

原文網址: https://kyushu.letsgojp.com/archives/609036/ © 樂吃購！日本 kyushu.letsgojp.com
:::

### [地鶏炭火焼 粋仙](https://maps.app.goo.gl/baj7LR2wYUpJnAcG9)

::: {.callout}
- $17:00 \sim 22:00$
- $4.2\ \textcolor{orange}{\bigstar} \ (686)$
- \$\$
- [menu](https://www.suisen-jidori.com)

「粋仙」是一間位於宮崎市中心的炭火燒地雞專門店，距離宮崎車站步行約5分鐘，交通相當方便。店內使用日向備長炭，將宮崎兩種地雞「地頭雞」和「赤雞」以炭火燒烤，鎖住肉汁並帶有獨特的炭香，肉質鮮嫩多汁又有嚼勁。除了燒烤，還提供當天新鮮處理的生雞肉料理，包括心臟、胗等部位，口感鮮美。店裡採用和風現代設計，是一棟獨棟建築，空間明亮舒適，設有吧台和座位區。此外，酒品種類豐富，有超過130款宮崎在地燒酎，推薦搭配地雞料理享用。

原文網址: https://kyushu.letsgojp.com/archives/537083/ © 樂吃購！日本 kyushu.letsgojp.com
:::

### [おぐら 本店](https://maps.app.goo.gl/Pd1MWNHCAXmGigqH8)

::: {.callout}
- $11:00 \sim 14:20$
- $17:00 \sim 19:50$
- $4.2\ \textcolor{orange}{\bigstar} \ (2988)$
- $\yen 1000 \sim \yen 2000$
- [menu](http://www.ogurachain.com/menu.html)

Ogura本店」位於宮崎市，是炸雞南蠻的發源地之一。店內選用鮮嫩的日向雞胸肉，經過油炸後外酥內嫩，再裹上由醬油與醋慢火熬製而成的甜醋醬，最後淋上手工製作的濃郁塔塔醬，酸甜滋味恰到好處。店內保留昭和時代的懷舊風格，來到這裡，不僅能品嚐宮崎洋食的經典美味，更能深刻感受當地的飲食文化。

原文網址: https://kyushu.letsgojp.com/archives/537083/ © 樂吃購！日本 kyushu.letsgojp.com
:::

### [桐木神楽堂 和菓子](https://maps.app.goo.gl/1z2ib3RX4iDgibUu8)

::: {.callout-note}
- $09:00 \sim 18:00$
- $4.3\ \textcolor{orange}{\bigstar} \ (111)$
:::

### [九州パンケーキカフェ 宮崎本店 九州鬆餅咖啡](https://maps.app.goo.gl/LsLpy9Lkqaf2emxG7)

::: {.callout-note}
- $08:00 \sim 16:30$
- $4.0\ \textcolor{orange}{\bigstar} \ (329)$
- $\yen 1000 \sim \yen 2000$
- [menu](http://www.kyushu-pancake.jp/miyazaki/)
:::