---
title: "宮崎"
format:
  html:
    navbar: false
    sidebar: japan-miyazaki
---

宮崎縣位於九州東南部，東邊有美麗的海岸線，西邊有九州山地及霧島連峰等雄偉的山岳景觀。其中，能享受美麗的自然風光和熱帶島嶼氛圍的景點眾多，度假設施也相當充實，作為富有南國風情的旅遊勝地而深受海內外旅人的歡迎。

宮崎縣還被譽為日本神話的故鄉，有許多流傳著古老神話及傳說的景點，可以領略到日本歷史和傳統文化的獨特魅力。

宮崎縣是日本最古老的史書《古事記》和《日本書紀》中所描述的「日向神話」的舞台。 在「日向神話」的一開始就描述了關於天神自眾神之國降臨到高千穗的場景。在被稱為「神話故鄉」的高千穂和青島等著名景點，可以欣賞到仙氣滿滿，充滿神秘氛圍的大自然景觀。

一年四季氣候溫暖宜人的宮崎縣，除了盛產芒果以外，以宮崎牛為代表的品牌牛肉、豬肉、地雞等美味食材也享譽全日本。

※《古事記》和《日本書紀》是記載日本神話、日本古代史的重要史籍 ([詳細資訊](https://www.gltjp.com/zh-hant/directory/item/15365/))。 \
※ [資料來源](https://www.gltjp.com/zh-hant/article/item/20236/)

## 地圖
```{python}
#| echo: False
from ipyleaflet import Map, Marker, basemaps, basemap_to_tiles, TileLayer
import leafmap.foliumap as leafmap

miyazaki = (31.90856140083178, 131.42189403602256)
m = leafmap.Map(
  width=400, 
  height=300, 
  center=miyazaki, 
  zoom=11,
  draw_control=False,
  measure_control=False)
m
```

## 住宿
#### [Prince Smart Inn Miyazaki](https://maps.app.goo.gl/AQZhgdkH6G7ZYyUS9)

- 星期一[公車路線](https://maps.app.goo.gl/Q5vwnZTMNJ5i9C569)
- 星期五 $06:45$ [去機場](https://maps.app.goo.gl/iAGAJ9jkmSHUGqwq8)
- $07:20$ 到機場
- $10:30$ 起飛


## 行程
#### [星期一](星期一.qmd)
#### [星期二](星期二.qmd)
#### [星期三](星期三.qmd)
#### [星期四](星期四.qmd)
#### [其他景點](景點.qmd)

## 美食
#### [高千穗峽周邊](food.qmd#高千穗峽周邊)
#### [青島周邊](food.qmd#青島)
#### [䶏戶周邊](food.qmd#䶏戶)
#### [飫肥城下町周邊](food.qmd#飫肥城下町)
#### [市區](food.qmd#市區)

## 所有地點 [https://maps.app.goo.gl/DokaNAW5grPGD5cv7](https://maps.app.goo.gl/DokaNAW5grPGD5cv7)

# 交通

::: {.callout-note collapse="false"}
宮崎當地交通票券推薦！「宮崎巴士一日券」
現在中華航空每周皆有固定航班從台灣直飛宮崎，如果各位打算從宮崎機場進到市區、或是當天預計都靠公車代步，非常推薦購買這張外國遊客限定的「宮崎巴士一日券」，價格為1000元日幣/張，只要是「宮崎交通」的巴士都可以搭乘喔！購買「宮崎巴士一日券」時需出示護照（留學生也可以購買）。可以在機場的資訊櫃台、宮崎車站、宮崎市區內多間飯店及巴士總站購得。

原文網址: https://kyushu.letsgojp.com/archives/609036/ © 樂吃購！日本 kyushu.letsgojp.com
:::

::: {.callout-note collapse="false"}
於宮崎市觀光時，推薦您搭乘連接宮崎車站和市中心的「GRUPPI」巴士。這些可愛的黃色或橙色 GRUPPI 巴士大約每12分鐘一班，從上午10:30左右開始運行於市中心。每趟車程只需100日圓，且可用現金或交通IC卡支付。歡迎搭乘！

如欲了解「GRUPPI」搭乘地點及時刻表等資訊，請參閱[網站](https://www.miyazaki-city.tourism.or.jp/traffic/12268)
:::


## 資料來源
- [https://www.kanko-miyazaki.jp/zh-TW](https://www.kanko-miyazaki.jp/zh-TW)
- [https://www.miyazaki-city.tourism.or.jp/zh_TW](https://www.miyazaki-city.tourism.or.jp/zh_TW)
- [https://takachiho-kanko.info/?stt_lang=zh-TW](https://takachiho-kanko.info/?stt_lang=zh-TW)
- [https://kyushu.letsgojp.com/archives/537083/](https://kyushu.letsgojp.com/archives/537083/)
- [https://littlebeartrips.com/miyazakiken-travel-spot/](https://littlebeartrips.com/miyazakiken-travel-spot/)
- [https://www.japan.travel/en/destinations/kyushu/miyazaki/](https://www.japan.travel/en/destinations/kyushu/miyazaki/)
- [https://rinosseros.blogspot.com/2024/02/miyazaki-coastline-sun-blue-skies-and.html](https://rinosseros.blogspot.com/2024/02/miyazaki-coastline-sun-blue-skies-and.html)
- [https://kyushu.letsgojp.com/archives/609036/](https://kyushu.letsgojp.com/archives/609036/)
- [https://www.kanko-miyazaki.jp/zh-TW/highlights/miyazaki_lunch](https://www.kanko-miyazaki.jp/zh-TW/highlights/miyazaki_lunch)
- [https://www.gltjp.com/zh-hant/article/item/20285/](https://www.gltjp.com/zh-hant/article/item/20285/)