---
title: 星期二
format:
    html:
        navbar: false
        sidebar: japan-miyazaki
---

# [高千穂地區](https://takachiho-kanko.info/?stt_lang=zh-TW)
# 交通
- [07:40 從飯店出發 先去高千穗天照鐵道](https://maps.app.goo.gl/dSdQ5oq9SxmEzNyd8) (～3小時30分鐘)
- 11:20 到 [高千穂峡](#高千穂峡)
- 下午05:30 前到[高千穂公車中心](https://maps.app.goo.gl/CXRTde7F7o8Kx43P9)
- 搭[回程最後一班](https://maps.app.goo.gl/wPagjBexJ5xJKz1y7) (20:30 到) \
回程班次出發時間 下午3:40, 4:25, 5:30

# [高千穗天照鐵道（高千穂あまてらす鉄道）](https://maps.app.goo.gl/ktHUAsJE19jLx6aL9)
- [官網](https://amaterasu-railway.jp)

::: {.callout-note collapse="true"}
## 能欣賞神話之鄉「高千穗」美景的超受歡迎鐵路
曾經深受旅人所喜愛的高千穗鐵道，於2005年面臨停止營運的狀況。為了能夠繼續活用這條路線，導入柴油引擎動力的小火車作為觀光用途。從高千穗站至高千穗橋距離5.1公里的路程中會穿過兩座隧道，以時速20公里行駛約需要30分鐘。

高千穗車站完整地保留了日本國鐵時代的建築，擁有濃厚懷舊氣氛的外觀。站內的展示區中展示著當年曾經使用過的機器和資料。同時附設有咖啡廳，在搭乘前後也可以在這裡稍事休息。另外也保存著舊高千穗鐵道時代的柴油車廂，可以到車廂內參觀，透過事前預約也可以體驗駕駛列車的樂趣。

高千穗小火車最多可以搭載30位乘客，1天內共計10車次。由熟悉高千穗鐵道的駕駛員擔任導覽員。鐵道迷們千萬不可錯過。因為不接受預約，週末假日的遊客眾多，建議提早購票為佳。

【受理時間】9:25～15:25　※不可事先預約\
【運行時間】9:40～15:40（1天10班※臨時班次除外）\
:::

::: {.callout-warning}
## 注意
運行時間為40分鐘一班 \
上午 9:40、10:20、11:00、11:40 \
下午12:20、1:00、1:40、2:20、3:00、3:40

車票$\yen 2000$ + 車站門票$\yen 100$

交通：從[高千穗巴士中心](https://maps.app.goo.gl/eZBL8YUdw7qjtF8y8)出發，步行10分鐘。
:::

# [高千穂峡](https://maps.app.goo.gl/dYbxeSob9ryteG7C6)

::: {.callout-note collapse="true"}
## 傳承日本神話的美麗高千穗溪谷
高千穗峽位於高千穗町，是日本知名的「神話之鄉」。這座溪谷因阿蘇山火山爆發而形成，斷崖高度約80公尺～約100公尺、長度達約7公里。這裡是日本的代表性風景勝地，獲指定為國家名勝、天然紀念物。

遊客可從步道眺望美麗的柱狀溪谷及瀑布等景色。尤其落差17公尺的真名井瀑布亦獲指定為日本瀑布百選，是象徵高千穗峽的風景。

峽谷兩側的玄武岩壁高達80公尺，形成高千穗峽的柱狀斷崖被稱為「柱狀節理」。 很久以前，由於阿蘇山的大爆炸而流出的火碎流冷卻凝固，經過漫長的歲月被侵蝕，形成了像現在這樣深邃而美麗的巖壁。

遊客可搭乘手划小船，近距離欣賞瀑布從峭壁上奔流而下的夢幻景象，特別是在晨霧或夕陽下，景色如詩如畫。此外，峽谷內還有步道，沿途可欣賞壯麗的自然美景與溪流，特別適合喜愛大自然的旅人。
:::

## [真名井の滝](https://maps.app.goo.gl/xR7FEw7Jn1Z9xTrK9)
可以說是高千穗峽的代名詞的著名瀑布，被選為日本瀑布100選。 據說天孫降臨時，由於這片土地上沒有水，天村雲命轉移水種的「天真名井」的水變成了瀑布流了下來。 從小船上仰望的瀑布很有魄力。 \
[出租船資訊連結](https://takachiho-kanko.info/boat/detail.php)

## [おのころ池](https://maps.app.goo.gl/oHypsdhLygUu5VRL9)
池塘裡有伊弉諾尊、伊弉冉尊兩神創造的島嶼「Onokoro島」。 在高千穗神社的大祭中，神轎在御之池繞了3圈進行禊。

## [月形](https://maps.app.goo.gl/Tkpy2W4Zh6LnJoGs8)
由於素戔嗚尊的粗暴，天照大神躲在天巖屋的「巖門開神話」之後，素戔嗚尊受到神明的審判被驅逐出高天原。 據說當時作為道歉的標誌，用表示天照大神的「日形」和沒有一半存在的「月形」來表達自己。 江戶末期的記錄中還留下了「月形、日形」的圖畫，但現在「日形」已經崩潰，只剩下「月形」。

## [鬼八の力石](https://maps.app.goo.gl/jBiPF3tpY3bqn8EJ6)
高千穗神社的祭神三毛入野命和破壞高千穗鄉一帶的荒神鬼八爭鬥時，據說是鬼八為了炫耀力量而扔的石頭。 重量估計為200噸。

#### 其它
::: {.callout-note collapse="true"}
#### [高千穂峡淡水魚水族館](https://maps.app.goo.gl/S74Rv1fEPav5jVy2A)
- $09:00 \sim 16:00$, 門票 $\yen 600$, [官網](https://www.town-takachiho.jp/top/soshiki/kikakukanko/2/3/313.html)
利用以[玉垂瀑布](https://maps.app.goo.gl/CTP9xJ64S4fuv7Lj7)
為水源的清澈泉水，以棲息在東科等五瀨川水系的淡水魚為中心，還有棲息在巴西、非洲的熱帶淡水魚、兩棲動物、鐵魚等稀有魚類 聚集了大約80種淡水魚、熱帶魚。

希望能夠作為來訪者的研修場所，也可以作為學習設施使用，對自然保護有一點幫助。
:::


## [高千穗神社](https://maps.app.goo.gl/4wQPUaoy82D3Ar6FA) 
- (從高千穗峽步行20分鐘)

::: {.callout-note collapse="false"}
## 每晚舉辦的傳統神樂必看！
高千穗神社已有超過1,900年歷史，是當地最重要的神社之一，供奉著天孫降臨的神祇。

高千穗神社以結緣之神而聞名。

用地內有樹齡約800年的「秩父杉」，以及同根生的2棵巨大杉樹「夫婦杉」。據說與伴侶攜手繞夫婦杉3圈就會獲得幸福，保佑良緣、夫妻和睦及子孫繁榮。

每年11月中旬起到隔年2月上旬，高千穗的各聚落都會舉辦「夜神樂」，一整晚向神明供奉三十三種神樂。而高千穗神社則在每天晚上8點起舉辦1小時的「高千穗神樂」，表演代表性的4種神樂。在夜神樂季節以外期間，也可欣賞日本的傳統神樂，廣受日本國內外的觀光客歡迎。（收取參觀費，須事先預約）
:::

#### 其它

#### [國見丘（国見ヶ丘）](https://maps.app.goo.gl/HSCho4pP2dY7QmGe6)

::: {.callout-note collapse="true"}
## 高千穗最著名的日出與雲海觀賞地
國見丘是高千穗最著名的日出與雲海觀賞地，標高513公尺，可俯瞰整個高千穗盆地，晴朗的秋冬清晨，這裡經常被夢幻的雲海覆蓋，猶如仙境。此外，這裡也是欣賞日出與星空的絕佳地點，被選為「日本百大日出景點」之一。
- [官網](https://takachiho-kanko.info/sightseeing/8/)
:::

#### [天安河原（あまのやすかわら）](https://maps.app.goo.gl/oJsbm1BG3m6gNRQJA)、[天岩戸神社](https://maps.app.goo.gl/81Wj4Fxn2Up3h8Rp8)
- [官網](https://amanoiwato-jinja.jp)
- [高千穗觀光協會](https://takachiho-kanko.info/sightseeing/6/)

::: {.callout-note collapse="true"}
## 知名日本神話「天岩戶神話」的舞台
天安河原位於從天岩戶神社步行約10分鐘的場所，即日本神話舞台的大洞穴。身為太陽神的天照大神躲藏在天岩戶中，世界因此陷入黑暗，引發無數災禍。據傳這片河原就是煩惱的眾神明聚在一起，商量如何取回光明的場所。傳聞在這個能量景點將石頭疊起並許願，就能實現願望，洞穴內疊起的眾多石堆呈現出神秘的氛圍。

天岩戶神社歷史悠久，也是日本現存最古老史書中所記載「天岩戶神話」的舞台。在神話中，身為太陽神的天照大御神對弟弟素盞鳴命的暴行感到憤怒，因而躲藏於名為天岩戶的岩石洞穴。天岩戶中便供奉著神明依附的御神體。這裡也是日本數一數二的知名能量景點。

天岩戶神社供奉著太陽神躲藏的天岩戶。傳說中眾神明在洞穴前製造出熱鬧的聲響，引誘天照大神出來而取回光明。岩戶川的兩岸分別鎮座著「西本宮」與「東本宮」，供奉御神體「天岩戶」的是西本宮，一天提供15次神職人員的參拜導覽服務。請一定要造訪知名日本神話「天岩戶神話」的舞台。
:::

### [＃高千穗美食](food.qmd#高千穗峽周邊)
