---
title: 星期四
format:
    html:
        navbar: false
        sidebar: japan-miyazaki
---

## [宮崎神宮](https://maps.app.goo.gl/B9vTajX1Vw76Mhbz7)
- $06:00 \sim 17:30$, [官網](https://miyazakijingu.or.jp)

::: {.callout-note collapse="false"}
## 以日本第一代天皇「神武天皇」為主神的神社
宮崎神宮供奉著日本第一代天皇「神武天皇」，是宮崎市內最受歡迎的神社，據說會保佑家庭平安、夫妻和睦、懷孕、生產。此外，由於神武天皇的日本建國神話，許多人會祈求保佑勝利或考試合格。在每年秋季舉辦的宮崎神宮大祭中，讓人聯想到古代的豪華遊行隊伍值得一看。這是暱稱為「神武天皇」的宮崎代表性祭典，受到當地居民愛戴。

其他還有祈求五穀豐收的祭神儀式及震撼力十足的流鏑馬（傳統騎馬射箭活動）等，一整年都會舉辦充滿古代特色的活動。
:::

## [宮崎県立美術館](https://maps.app.goo.gl/jkuuTHZjAM7U6QQt5)
- $10:00 \sim 18:00$, **週一公休** [官網](https://www.miyazaki-archive.jp/bijutsu/)

::: {.callout-tip collapse="false"}
## [宮崎県立美術館 展覽](https://maps.app.goo.gl/jkuuTHZjAM7U6QQt5)
開館30週年紀念

### [ひろしま美術館コレクション](https://www.miyazaki-archive.jp/bijutsu/box/tokubetsu.html#hiroshima) $\yen 1300$ $2025/10/04 \sim 2025/11/24$
廣島美術館收藏了以印象派為中心的19世紀到20世紀代表西方近代美術的畫家們的作品，其收藏品在國內外都獲得了很高的評價，同時收集了同時代的日本美術的優品。 也為人所知。

在本次展覽中，從廣島美術館的收藏中，除了印象派的莫奈、雷諾阿、代表20世紀的畢加索、馬蒂斯等人的作品外，還有奠定了明治時期日本油畫基礎的淺井忠和黑田清輝，日本獨有的 介紹在迎來了洋畫黃金時代的昭和時期活躍的梅原龍三郎等人的作品共70件。

透過廣島美術館的珠玉作品，請一邊欣賞西方近代美術史的展開和日本近代洋畫的探索過程，一邊欣賞西方和日本美的競演。

### [第3期コレクション展](https://www.miyazaki-archive.jp/bijutsu/box/collection.html) 無料 $2025/10/11 \sim /2025/12/21$
介紹本館收藏作品的收藏展。 鄉土作家自不必說，還介紹了很多海外著名作家的作品，

也受到來自縣外的客人的好評。 收藏展每年舉辦4次，設定豐富多彩的主題。

宮崎縣立美術館在令和7（2025）年10月迎來了開館30週年。 迄今為止，根據「鄉土出身的作家以及與本縣有淵源的作品」「適合展望我國美術潮流的作品」「海外優秀作品」這3個方針進行收集，目前收藏了約4,200件作品。

去年，從這些收藏中，徵集了大家想看的作品、希望展示的作品，收到了超過1500個請求。 這次，根據這些要求選出的前20名作品作為本館的「最佳最佳」進行展示，同時以前50名的作品為中心，同時介紹收藏的歷史和與作品相關的插曲。
:::


## [宮崎縣綜合博物館](https://maps.app.goo.gl/DvMcDVKsLNzkXiPD6)
- [官網](http://www.miyazaki-archive.jp/museum/)

::: {.callout-note collapse="false"}
## 簡介
綜合博物館內展出棲息於宮崎的動植物生態紀念雕像及實體展品，並以充滿魄力的實景模型重現古代人狩獵的模樣。用地內的民宅園是將建築風格獨特的4棟民宅，從縣內各地移建復原建成，被登錄為日本國家及宮崎縣的重要文化財。（常設展免費）

營業時間 : 平日9點～17點 週二公休\
:::

::: {.callout-note collapse="false"}
## 展覽
特別展　焼酎のすゝめ　～「宮崎の本格焼酎」の歴史と酒造と発酵のふしぎ～

特別展 燒酒的介紹 ～「宮崎的正宗燒酒」的歷史和釀酒和發酵的不可思議～

飲むだけが「焼酎」じゃない！🍶
「焼酎」の魅力を歴史と科学でひも解きます。

喝的不僅僅是「燒酒」！ 🍶 用歷史和科學解開「燒酒」的魅力。

開催期間 10月18日（土） - 11月30日（日）\
観覧時間 9：00～17：00（入館は16：30まで）
:::

# 其他參照這個[頁面](景點.qmd)
