---
title: 星期三
format:
    html:
        navbar: false
        sidebar: japan-miyazaki
---
# 日南海岸地區

## 交通

::: {.callout-tip collapse="false"}
## 方案 A 出發 $\to$ 青島神社 $\to$ 飫肥城下町 $\to$ 返回
**出發**

- $07:40$ 出發 \
- [公車路線](https://maps.app.goo.gl/a1ScVYiUhupH61Z76)
- $08:40$ 到[青島神社](#青島神社)

$09:00\quad$ 到[青島神社](#青島神社)
- 在[青島](#青島) 附近活動

$12:20\quad$ [出發](https://maps.app.goo.gl/xFFmiKdKgCJRPJmR9) 去 [飫肥城下町](#飫肥城下町)

$\ldots$ [^1]

- 回[市區](景點.qmd#市區)逛
- [公車](https://maps.app.goo.gl/o34eBzL7SNW9xLyB9)
:::

::: {.callout-note collapse="true"}
## 方案 B 出發 $\to$ 鵜戶神宮 $\to$ 青島神社 $\to$ 返回
[參照](https://travistotravel.com/2024/09/20/宮崎自由行鵜戶神宮/)

$09:30\quad$ [出發](https://maps.app.goo.gl/L7ZWJEqdx867fwwh6) \
$11:20\quad$ 到[鵜戶神宮](鵜戶神宮) \
$13:00\quad$ [出發](https://maps.app.goo.gl/yGYHajWdLB5SzEWx8) \
$14:10\quad$ 到[青島神社](#青島神社) \

$\ldots$ [^1]

- 回[市區](景點.qmd#市區)逛
- [公車](https://maps.app.goo.gl/mnVhRm3Bs9MtMhtZ7)
:::


::: {.callout-warning collapse="true"}
## 方案 C 出發 $\to$ 青島神社 $\to$ 日南太陽花園(週三公休) $\to$ 鵜戶神宮 $\to$ 返回

- $07:40$ 出發 \
- [公車路線](https://maps.app.goo.gl/a1ScVYiUhupH61Z76)
- $08:40$ 到[青島神社](#青島神社)

- 在[青島](#青島)待 $3$ 小時 $+$ 吃午餐
- $12:20$ 出發去 [日南太陽花園](#日南太陽花園)
- 搭[30分鐘公車再步行25分鐘](https://maps.app.goo.gl/moB197NHNJYDoS1FA) $\sim\yen 1000$
- 下午 $01:30$ 到

在[日南太陽花園](#日南太陽花園)待 $1$ 小時 $30$ 分鐘

- 下午 $03:00$ 出發
- [步行10分鐘+搭5分鐘公車+步行10分鐘](https://maps.app.goo.gl/RWSWrTdWuU48tKUM6)去[鵜戶神宮](鵜戶神宮) $\sim\yen 250$

[鵜戶神宮](鵜戶神宮) 待 $1$ 小時

**[下午 04:32 返回](https://maps.app.goo.gl/r4RKMYwMzmkKD6Ka6)** $\sim 1$ 小時, $\sim\yen 1550$

:::

::: {.callout-note collapse="true"}
## 方案 D 出發 $\to$ 青島神社 $\to$ 返回
**出發**

- $07:40$ 出發 \
- [公車路線](https://maps.app.goo.gl/a1ScVYiUhupH61Z76)
- $08:40$ 到[青島神社](#青島神社)
- 在[青島](#青島) 附近活動

$\ldots$ [^1]

- 回[市區](景點.qmd#市區)逛
- [公車](https://maps.app.goo.gl/mnVhRm3Bs9MtMhtZ7)
:::


# [青島神社](https://maps.app.goo.gl/7uPZhi1e2QvnZ1ay6)
- [青島觀光網站](https://www.miyazaki-city.tourism.or.jp/spot/10001)

::: {.callout-note collapse="false"}
## 受亞熱帶植物與奇岩怪石圍繞的神祕島嶼
青島整體生長著茂密的亞熱帶植物，大自然景觀豐富，是一座周長1.5公里的小島。外觀彷彿巨大洗衣板的「鬼之洗衣板」圍繞著青島，其為經年累月受海浪侵蝕形成的奇岩群，作為珍貴文化財而受到保護。這裡是傳承著知名日本神話之地，也是廣受歡迎的神聖場所，蘊含神秘的力量。

青島中央有以結緣而聞名的青島神社，島嶼整體皆屬於神社用地。神社供應心型繪馬等祈求戀愛順利的各種商品。深受尋找心型裝飾的旅客喜愛。

此外，島嶼周邊有餐廳、商店及海灘，可享受海上運動、海水浴、用餐及購物。青島地區是宮崎的熱門觀光景點。
:::

::: {.callout-note collapse="true"}
#### 堀切峠 (ほりきりとうげ)
- [觀光網站](https://www.miyazaki-city.tourism.or.jp/spot/10006)

瀰漫著南國風情的鳳凰林蔭道，蔚藍的大海和藍天的絕景。 可以說是宮崎市的象徵、代表的風景就是這個堀切峠。

位於從宮崎市中心沿國道220號南下，從縣道377號的山間沿著海岸穿過的地方。

跑過山路，眼前出現鳳凰和藍色的海景的瞬間，發出感嘆的聲音。

從海岸邊俯瞰大海，從浪間可以瞥見奇巖「鬼的洗衣板」，讓人忘記時間眺望的絕景。

附近有「路邊站鳳凰」，可以一邊欣賞美景一邊品嚐軟冰淇淋和當地美食，是宮崎屈指可數的自駕路線。
:::


# [日南太陽花園](https://maps.app.goo.gl/Hbg6fq3Q4gkgxo5b7) 
- $09:30 \sim 17:00$, 週三公休, 門票 $\yen 1000$ [官網](http://sun-messe.co.jp)

::: {.callout-note collapse="true"}
## 可欣賞魄力十足的摩艾石像與海洋美景的公園
日南太陽花園佔地20公頃，園內風景優美，視野開闊。除了地標「摩艾石像」之外，還有感謝地球鐘、太陽之丘、展望台等景點。

站在美麗的丘陵之上，眺望著日南海岸浩渺無垠、海天一色的壯觀景色，會感到心曠神怡。

這裡還是一處適合家人遊玩的公園。餐廳、禮品店、觀光牧場、溫泉等設施一應俱全。
:::

# [鵜戶神宮](https://maps.app.goo.gl/u93WEmijRjvsnVbY9)
- $06:00 \sim 18:00$, [官網](https://www.udojingu.or.jp)

::: {.callout-note collapse="false"}
## 南九州的代表性神社，本殿位於洞穴中
鵜戶神宮的朱漆本殿色彩鮮艷，位於往大海突出的海岬洞穴內。這是南九州的代表性神社，位於宮崎縣南部的日南海岸。據傳其保佑順產、育兒、結緣等，長年以來深受當地居民愛戴。這裡的「投擲運玉」十分有名，據說在許下願望的同時，男性以左手、女性以右手扔出「運玉」，若能投進稱為龜石的岩石凹洞內，即可實現心願。在通往本殿的參道上，可將日向灘的美景盡收眼底。海岬周遭林立著形形色色的岩石，強力的海浪拍打其上。

穿過鵜戶神宮的神門後，步行約20分鐘即可抵達波切神社。在極為靠近大海的洞穴中，鳥居與小小的神社就鎮守於此。這是一處呈現夢幻神秘氣氛的能量景點。參道有如山路一般，容易滑倒且較陡，建議穿著不易滑倒的鞋子前往。

[閱讀更多](https://breathetokyo.jp/journals/miyazaki-nichinan-udo/)
:::

# [飫肥城下町](https://maps.app.goo.gl/ECS1Y1f5bGK8b7Nm9)
::: {.callout-note collapse="false"}
## 保有美麗石牆及武士宅邸的城下町
1588年起約280年間，飫肥城下町作為飫肥藩的城下町而繁榮，現今仍留有飫肥石的石牆及以飫肥杉打造的武士宅邸等。歷史悠久的美麗街道又稱為「九州的小京都」，保存著傳統建築物。街上以飫肥城大手門為中心，林立著武士宅邸及商店，也有可參觀的設施，能在城下町盡情散步。在四半的射箭場可挑戰飫肥的傳統半弓「四半的」，體驗武士的氣氛。飫肥城歷史資料館內展示著甲冑、刀劍、武器及服飾等，值得一看。而在飫肥城舊本丸遺址，樹齡140年的飫肥杉與苔蘚覆蓋的地面十分唯美，被稱為「療癒森林」。這裡不僅讓人心靈祥和，也是絕佳的拍照景點，推薦來一探究竟。

若要吃遍、逛遍飫肥小鎮，也推薦使用「小步地圖」，地圖上附有5張能獲得飫肥名產等伴手禮的商品兌換券與設施入館券。可一邊享用入口即化且甜味優雅的「飫肥煎餅」、黑糖溫和甜味令人欲罷不能的甜不辣「飫肥天」、口感彷彿布丁的厚燒卵等絕佳飫肥名產，一邊盡情漫步於保留著江戶時代樣貌的城下町。

[飫肥城](https://travistotravel.com/2024/09/21/宮崎自由行飫肥城飫/)
:::


[^1]: 自己想👍 ¯\\\_(ツ)\_/¯ 