---
title: 其它景點
format:
    html:
        navbar: false
        sidebar: japan-miyazaki
---

# 市區

## [Direx Yoshimura ダイレックス 吉村店](https://maps.app.goo.gl/NvYETQAKTBRJAfXe7?g_st=ipc)

::: {.callout}
折扣店
:::

## [Hard Off Miyazaki Ichinomiya ハードオフ 宮崎一の宮店](https://maps.app.goo.gl/zEitLva3qa8mD9n26?g_st=ipc)

::: {.callout}
二手店
:::

## [アートハウスゲルボア](https://maps.app.goo.gl/NLSToosU9Z4ce6u4A?g_st=ipc)

::: {.callout}
畫具
:::

## [西橘](https://maps.app.goo.gl/omc5EPuNghk825i36)

::: {.callout-note collapse="false"}
## 宮崎最大的鬧區
西橘是宮崎最大的美食街區，以西橘通為中心，包含相鄰的中央通、惠比壽通、高松通、西銀座通等。

當地居民暱稱其為「西橘」。道路兩側掛著數個暖色系的燈籠，光是看著隨風搖曳的燈火，就讓人不禁期待著這裡的復古氣氛。

在西橘地區，有1,500間以上的餐廳櫛比鱗次。可品嘗當地美味下酒菜的居酒屋、時髦酒吧、立飲店、烤肉及義大利料理等，都凝聚在這小小的街道上，最適合來喝透透！

這裡也有許多一個人可以輕鬆進入的店家，一定能找到自己的愛店。如果出差或觀光時來到宮崎，不妨就前往西橘！
:::

## [AEON MALL宮崎](https://maps.app.goo.gl/XijL5sQeSahuPRcz7)
- $10:00 \sim 21:00$

::: {.callout-note collapse="false"}
## AEON MALL宮崎
「AEON MALL宮崎」是宮崎市大型購物中心，擁有超過250家店鋪，提供時尚服飾、美妝和生活用品，滿足多元購物需求，餐飲區涵蓋當地料理、異國料理，選擇十分豐富。另外還有親子友善設計設有兒童遊樂區與休息空間，適合家庭同遊，交通也方便，無論自駕或搭乘公車都方便。

原文網址: https://kyushu.letsgojp.com/archives/537083/ © 樂吃購！日本 kyushu.letsgojp.com
:::

## [宮崎山形屋](https://maps.app.goo.gl/JUDvNjTTwjzfZypa7)
- $10:00 \sim 19:00$

::: {.callout-note collapse="false"}
## 宮崎山形屋
「宮崎山形屋」是宮崎市中心最具歷史的百貨，創業超過90年，融合昭和風情與現代設計，是旅途中值得駐足的一站。本館販售日用品與老字號店鋪，新館則引進COACH、TOMORROWLAND等國際品牌，購物選擇多元，地下一樓美食特產區匯聚宮崎牛便當與九州限定甜點，無論品味在地風情或挑選伴手禮，都能一次滿足。

原文網址: https://kyushu.letsgojp.com/archives/537083/ © 樂吃購！日本 kyushu.letsgojp.com
:::

## 沿著大淀川 騎腳踏車

::: {.callout-note collapse="false"}
## 簡介
大淀川是貫穿這座城市的主要渠道。 從[宮崎市市政府](https://maps.app.goo.gl/yPVN8SPe2LqydiSp6)出發，一條專門的腳踏車道沿著河的長度延伸，是一條美麗、風景優美的騎行，基本上沒有汽車。帶上自己的腳踏車或在[宮崎站的旅遊資訊中心](https://maps.app.goo.gl/Ls5kAK1GbbYbZo6CA)或[捷安特腳踏車店 GIANT STORE Miyazaki](https://maps.app.goo.gl/CCv22Y7iQ3wcQrsr7)租一輛。
:::

## [宮崎県立平和台公園](https://maps.app.goo.gl/tvaTFCqcxJt5UMQJA)

::: {.callout-note collapse="false"}
## 簡介
廣闊的平和臺公園距離城市以北僅10分鐘車程，是放鬆、散步和瞭解日本歷史的絕佳場所。 公園的主要特色是37米高的Hakko Ichiu紀念碑，現在是和平紀念碑，它是戰時大日本帝國時期用石頭建造的。 Hakko Ichiu的意思是「世界的八個角落在一個屋簷下」，這是建造時使用的口號。 你可以爬上臺階，欣賞公園和城市的壯麗景色。 平和大公園還有許多複製品粘土士兵排列在小路上，被稱為哈尼瓦。 它們是從附近的齋藤巴魯古墳的墳墓中挖掘出來的。
:::



## [Florante宮崎 フローランテ宮崎](https://maps.app.goo.gl/XFL3pCzDJobYaqHX8)
- $09:00 \sim 17:00$, 門票 $\yen 600$ **週二公休** [官網](https://www.florante.or.jp)

::: {.callout-note collapse="false"}
## 可欣賞四季花卉並參加活動的人氣景點
FLORANTE宮崎是一座都市型植物公園，無論何時都能欣賞到四季各異的花卉美景，園內種植了超過15萬株以上的花卉與植物，全年可欣賞不同種類的美麗花海。特別是在冬季，這裡會舉辦盛大的燈飾展覽，夢幻的燈光秀讓整個園區宛如童話世界。公園內的玻璃溫室與花藝展覽館也展示了宮崎的熱帶植物，讓遊客能夠深入了解當地的自然生態。
:::

## [宮崎縣廳](https://maps.app.goo.gl/kzSgL5vYKBtxTRL4A)

::: {.callout-note collapse="false"}
## 九州最古老！日本國家登錄有形文化財的宮崎縣廳
縣廳本館建於1932年，在日本國內是第4古老的現役都道府縣廳舍，在九州則是最古老的縣廳。其為近世哥德式建築，內部裝潢採用豪華裝飾及彩色玻璃圓窗等。

縣廳舉辦免費的參觀行程，讓民眾能夠更加了解縣廳。導覽義工會說明並導覽縣廳的精彩看點等。個人參加的定時行程不須事先報名即可參加。（僅提供日文服務）

此外，縣廳本館隔壁的「宮崎物產館KONNE」展示、銷售眾多宮崎的食品、工藝品。要買宮崎的伴手禮時，不妨順路前往選購。

營業時間 : 平日8點30分～17點15分 六日公休\
【定時行程】\
- 每月第1、第3個週三　10:00～12:00（受理：至11:30）\
- 每月第4個週五　16:00～17:15（受理：至16:45）\
- 每月第1個週日　10:30～12:00（受理：至11:30）\
（註）週三、週五適逢國定假日時，不舉辦行程。 \
:::

## [宮崎科學技術館](https://maps.app.goo.gl/NCufVUduQ1a2gsALA)
- [官網](https://cosmoland.miyabunkyo.com)

::: {.callout-note collapse="false"}
## 簡介
來到宮崎科學技術館，可透過實驗表演及手作教室等體驗，感受宇宙的不可思議及科學的樂趣。在這裡不僅可和全球僅有2個的阿波羅11號登月小艇實體尺寸模型拍紀念照，也可參觀九州最大的圓頂天文館。館內還會舉辦大人小孩都能盡興的活動。

營業時間 : 平日9點～16點30分 週一公休\
:::



# 一點遠

## [藏元 綾 酒泉之杜](https://maps.app.goo.gl/S1J1oRyUsUCrKdN16)
- [官網](https://kuramoto-aya-shusennomori.jp)

::: {.callout-note collapse="false"}
## 可參觀釀酒廠及試飲，美酒的主題樂園
位於綾町的雲海酒造直營的設施，當地有日本規模最大的闊葉林。其利用闊葉林孕育出的清水來釀酒。

除了正宗燒酎釀酒廠及日本酒釀酒廠之外，這裡也有葡萄酒莊「雲海葡萄酒釀造所」、啤酒釀造所。在「綾自然藏見學館」可參觀釀酒過程（須事先預約），參觀後還可試飲當地啤酒及酒精飲料。另外也可製作原創酒瓶及金屬徽章。

這裡也設有銷售名酒及宮崎特產的商店，以及運用當地食材供應料理的餐廳。

推薦參觀用地內玻璃工藝作家「黑木國昭」的工坊。黑木的卓越技術獲國家讚揚為「現代名工」，深受日本國內外歡迎。工坊內銷售著其原創作品。

營業時間
- 10:00～17:00（依設施而異）

公休日
- 週一、週二（適逢國定假日時順延至次日）
:::

## [西都原古墳群](https://maps.app.goo.gl/PAMparT649BBq7Uh8)
- [官網](https://www.kanko-miyazaki.jp/spot/1016)

::: {.callout-note collapse="true"}
## 可一窺古代日本的珍貴史蹟　日本規模最大的古墳群
西都原古墳群是日本規模最大的古墳群之一，擁有300多座古墳，部分可追溯至4世紀至7世紀，是研究古代日本歷史的重要遺跡。這裡也是宮崎最著名的賞花勝地，每到春天，數萬株油菜花與櫻花同時盛開，形成壯麗的金黃與粉色花海；秋天則有遍地的波斯菊，景色夢幻。此外，宮崎縣立西都原考古博物館展示了古墳時代的文物，讓遊客深入了解日本古代文化。（考古博物館亦免費）

被稱為日本最大的古墳群的「西都原古墳群」。 也被認定為日本遺產，東西約2.6km，南北約4.2km的廣闊臺地上散佈著300多座古墳。 一帶是公園，是一邊享受古代氛圍一邊享受散步和娛樂的休息場所，是深受許多人喜愛的景點。 春天是櫻花和油菜花，夏天是向日葵，秋天是波斯菊，用四季不同的花來裝飾。

在西都原古墳群中擁有稀有結構的「鬼之窟」，是古墳群中唯一有開口的橫穴式石室的圓墳，可以參觀內部。 也是與神話有淵源的景點，據說是愛上美麗的小花咲夜姬的鬼一夜建成的。 另外，因為是宮內廳管理的陵墓參考地，所以不在特別史蹟「西都原古墳群」的指定範圍內，但國內最大的扇貝形古墳「男狹穗冢」和九州最大規模的前方後圓墳「女狹穗冢」也 必看！ 據說是尼尼吉諾米科託及其妻子·科諾哈納薩庫亞希梅睡覺的地方，**每年11月**的「古墳節」都會舉行一年一度的特別參拜。

將廣闊的古墳群整體視為展品的野外博物館「西都原考古博物館」和古代生活體驗館，是充滿浪漫氣息的古代日向資訊傳播基地。 西都原指導中心「小花館」是當地產品銷售和餐廳的綜合指導設施。 是想一起去的景點。
:::

## [綾の照葉大吊橋](https://maps.app.goo.gl/QEoQDwFuY7MYF9Wr7)

::: {.callout-note collapse="true"}
## 橫跨日本規模最大闊葉林的大吊橋
這座大吊橋橫跨於九州中央山地國定公園內的綾川溪谷，高142公尺、長250公尺，是日本國內規模最大的步道吊橋之一。走在吊橋上，可體驗到彷彿空中散步的刺激體驗，日本最廣闊的闊葉林與天空壯觀全景就在眼前。

照葉大吊橋所在的綾町已登錄為聯合國教科文組織生態公園，穿過吊橋後有一條約2公里的自然步道，可享受森林浴。若想觀察闊葉林中的珍貴動植物，也可選擇與導遊一起漫步森林的行程，所需時間約3小時（須事先申請，僅提供日文服務）。在照葉大吊橋附近的照葉樹林文化館中，可學習闊葉林及森林生物的知識。
:::



# 好遠

## [都農葡萄酒莊](https://maps.app.goo.gl/QEgQeDLQrDjc9ymQ6)
- $09:30 \sim 17:00$, [官網](https://tsunowine.com/)

::: {.callout-note collapse="true"}
## 全球矚目的葡萄酒「都農葡萄酒」
都農葡萄酒莊位於可一覽宮崎平原及日向灘的美景景點。其葡萄酒僅使用在都農町採收的尾鈴葡萄釀造，獲全球盛讚，在日本國內外也榮獲多項大獎。在酒莊之旅中可在釀酒師的導覽下，參觀葡萄田及釀酒設施，並試飲葡萄酒。
烘焙咖啡廳販售可搭配都農葡萄酒品嘗的精緻麵包，能享用這裡獨一無二的麵包。
每年11月左右還會舉辦「都農葡萄酒收穫祭」，吸引許多遊客造訪。

營業時間
- 【酒莊商店】9:30～17:00
- 【TSUNO WINE & BAKERY】10:00～售罄　※飲料營業至16:00

公休日
- 【酒莊商店】年底年初
- 【TSUNO WINE & BAKERY】週一、週二、週三（適逢國定假日當週將變更營業日）
:::

## [幸島](https://maps.app.goo.gl/JBv7AtySVGtRFY7p7)

::: {.callout-note collapse="true"}
## 以會清洗地瓜來食用的猴子聞名全球的島嶼

這座無人島位於距離宮崎縣南部石波海岸約200公尺的近海上。搭船只需5分鐘即可抵達，是一座周長約3.5公里、面積約32公頃的小島。目前棲息著約90隻的日本獼猴，被指定為日本的國家天然紀念物「幸島猴棲息地」。1953年左右，1隻猴子開始了「清洗地瓜行動」，用海水清洗地瓜來食用，該行動被其他猴子及其子孫傳承下來，因而以「具有文化的猴子」而聞名全球。幸島也是知名的「日本靈長類學發源地」，有許多研究學者造訪幸島。
:::

## [出之山公園](https://maps.app.goo.gl/cbsyq61bYEEJGwZr9)

::: {.callout-note collapse="true"}
## 「名水百選」之一

被選為全國名水百選之一，有泉水湧出的公園。
5月下旬～6月上旬可見成群螢火蟲飛舞，公園內有可以品嚐鯉魚，鱒魚，鱘魚的餐廳，還有可觀賞130種1,500隻淡水魚的水族館。
:::

## [陣之池](https://maps.app.goo.gl/SnwmMMAKio5b1xWx7)

::: {.callout-note collapse="true"}
## 簡介
陣之池是大小兩座湧泉池，位於蝦野市的東北部。小池清澈透明見底，葉隙透出的陽光會隨時段變化角度，可欣賞各式各樣的色彩變化。翠綠色的水面夢幻無比。
:::

## [日本三大秘境 椎葉村](https://maps.app.goo.gl/nzWXMKkEYCNArXbC7)

::: {.callout-note collapse="true"}
## 日本三大秘境　彷彿飄浮空中的梯田美景
椎葉村受超過1,000公尺高的群山圍繞，坐落於自然景觀豐富的山間地帶。村子的96%是山林，斜坡多，被譽為日本三大秘境之一。

山間的民宅及田地運用在陡坡生活的智慧與努力設計而成。十根川聚落的美麗石牆與人稱椎葉型的細長傳統民宅為其特色，聚落最上層有開放內部參觀的設施，可一邊欣賞群山美景，一邊做瑜珈，或製作椎葉的傳統美食「菜豆腐」等。其他還有許多可盡情享受山村生活的體驗，例如製作蒟蒻、登山健行、採蘑菇、採山菜、騎電動登山車等。

在標高約450公尺的九州山地，沿著山脊有約100片連綿的梯田。由於彷彿飄浮在空中，此梯田群有「仙人的梯田」之稱，又名「椎葉的馬丘比丘」，是椎葉獨一無二的美景。
當地現今仍重視過往的習慣及傳統文化，傳統藝能的椎葉神樂被指定為日本的重要文化財。此外，這裡的燒墾農業完全不使用肥料與農藥，在日本只有到椎葉才能看見這種傳統農法。
此種農業系統及傳統文化受到認可，與鄰近的高千穗町、日之影町、五瀨町、諸塚村一同於2015年獲認證為世界農業遺產。
:::


## [都井岬](https://maps.app.goo.gl/Ygyww5FjNjsXaJ9g6)
- [官網](https://www.kanko-miyazaki.jp/spot/1002)

::: {.callout-note collapse="true"}
## 日本原生馬棲息處　宮崎最南端的海岬
都井岬是日本唯一可見野生馬群的海岬，這些馬匹被稱為「御崎馬」，是江戶時代遺留下來的品種，至今仍自由地生活在岬角草原上。遊客可以近距離欣賞這些優雅的馬匹，同時眺望無邊際的太平洋。岬角的燈塔也是熱門拍照地點，特別是在夕陽時分，景色浪漫至極。
:::

## [生駒高原](https://maps.app.goo.gl/VMwFrCmV1vBwpwhn6)
- $09:00 \sim 16:30$, 門票 $\yen 600$, [官網](https://ikomakougen.com)

::: {.callout-note collapse="true"}
## 在雄偉霧島連山山腳下的賞花名勝
位於標高540公尺處的高原，可將小林市內一覽無遺。約9萬平方公尺的用地以霧島連山為背景，是一片盛開四季花卉的花田。其為宮崎縣內數一數二的賞花名勝，也是眾多遊客造訪的熱門景點。4月中旬起可見約15萬株的花菱草、冰島罌粟，6月則為繡球花，9月中旬起可欣賞紅色的地膚草。10上旬起有約100萬株大波斯菊開滿整片高原。

這裡所見之處皆是花朵，可在花叢中悠閒散步，還可從數個設置好的觀景點拍下美麗花田的照片。深受歡迎的濃郁霜淇淋也推薦一定要品嘗看看。

此外，高原內有「小林生駒高原葡萄酒工房」，這間酒莊自釀葡萄酒，百分百使用當地小林產葡萄。其致力釀造出當地居民也喜愛的葡萄酒，不僅是正宗葡萄酒，也釀製順口、適合搭配新鮮當地食材的當地特色葡萄酒。
:::

## [蝦野高原](https://maps.app.goo.gl/pgiGRxCtDSvGTTyM7)
- [官網](https://www.kagoshima-kankou.com/guide/50927)

::: {.callout-note collapse="true"}
## 恣意享受火山形成的美麗景觀與大自然
蝦野高原位於霧島連峰的山麓，是九州最受歡迎的高原景點之一，擁有壯麗的火山湖與登山步道。這裡最大的特色是硫磺山噴氣孔，遊客可以看到地底不斷冒出的白色煙霧，感受大自然的震撼。此外，高原上還有多條健行步道，可通往不動池、六觀音御池與白紫池等風景如畫的火山湖。秋天時，整片山頭染上紅葉，景色如詩如畫，是登山健行與賞楓的最佳地點。
:::

## [馬之背斷崖（馬ケ背の断崖絶壁）](https://maps.app.goo.gl/KncEXnuNGwxyRaCv5)
- [官網](https://www.kanko-miyazaki.jp/spot/1105)

::: {.callout-note collapse="true"}
## 斷崖與太平洋美景！日向的代表性風景勝地
馬之背斷崖是九州最高的海崖，懸崖高度超過70公尺，垂直落入太平洋，形成壯觀的海岸景觀。這裡的海蝕岩壁綿延約1公里，與沖繩的萬座毛相似，但更為陡峭壯觀。從觀景台遠望，藍色大海與峭壁交織成一幅壯麗畫卷，特別是在清晨或黃昏，景色更顯夢幻。此外，這裡還是觀察**黑尾鷗（ウミネコ）**的絕佳地點，春秋時節可見成群海鳥在懸崖邊飛翔。
:::

## [大御神社](https://maps.app.goo.gl/h6zEzbSYxTtrXz1z9)
- [官網](https://oomijinja.com)

::: {.callout-note collapse="true"}
## 坐落於絕美大海之地，吉祥的能量景點
大御神社建於日向岬的柱狀岩上，可一覽太平洋美景，供奉著太陽神「天照大御神」。用地內有出現在日本國歌歌詞中的「細石」群，規模為日本國內最大。

日本橄欖球國家代表隊到宮崎集訓時曾祈願勝利，並奪得歷史性勝利，因此這裡也成為備受矚目的吉利神社。

往用地東側走去，可看見洞穴內的鵜戶神社。從洞穴深處往外看，洞穴入口附近外觀彷彿「昇龍」，因此一般認為這是龍神信仰的遺跡。這裡也是充滿古代浪漫氣息的地點之一。
:::

## [克魯斯之海](https://maps.app.goo.gl/ME17YK9vSuUQZ44t5)

::: {.callout-note collapse="true"}
## 眺望大自然打造的神祕景色
巨大的柱狀岩石受波浪侵蝕，往東西龜裂約200公尺，南北為約220公尺，從上方看起來有如十字形，因此以葡萄牙文的「十字」（cruz）命名。

這個十字形與一旁的岩場組合起來，看起來就像是日文中意為「實現」的漢字「叶」，因此據說造訪此處即可實現願望。
:::

## [愛宕山展望台](https://maps.app.goo.gl/2bTPmggyrYwX79co7)

::: {.callout-note collapse="true"}
## 簡介
愛宕山是日向市的最高點，標高251公尺，擁有360度環繞的壯觀視野，可遠眺日向市、太平洋與周圍的群山。這裡是欣賞日出與夜景的絕佳地點，特別是在秋冬季節，清晨時分有機會看到壯麗的雲海景象，讓整座山頭宛如仙境。此外，愛宕山展望台設有步道與觀景設施，是健行與親子遊的好去處。
:::

## [燒酎之里 霧島工廠花園](https://maps.app.goo.gl/TopckJY5PTeraURc8)
- [官網](http://www.kirishima-fg.jp/)

::: {.callout-note collapse="true"}
## 認識、品味霧島土地孕育出的燒酎歷史
霧島酒造是以「白霧島」、「黑霧島」等正宗芋燒酎聞名的燒酎釀造商，銷售額位居日本全國龍頭。此即霧島酒造的直營花園公園。

KIRISHIMA WALK FACTORY開放民眾參觀霧島燒酎的製程（須預約），最後還可試飲。在霧之藏博物館可學習到芋燒酎相關知識，例如為何要在這塊土地釀製燒酎等。此外，在KIRISHIMA ECO FACTORY可透過藝術品與影片，實際了解霧島酒造的燒酎釀造是循環型的環保活動。來到霧之藏釀酒廠，可購買燒酎、原創周邊商品及九州特產。此外，還可參觀釀造啤酒的釀酒窯。這裡也有餐廳，可享用精釀啤酒及使用當地食材製作的料理。另外還有現烤麵包深受歡迎的霧之藏烘焙坊。
廣闊用地內盛開著季節花卉，是彷彿公園一般的休憩場所。可在此散步或野餐，度過悠閒時光。

營業時間
- 商店　9:00～18:30

餐廳
- 午餐時段 11:00～15:00（最後點餐時間：14:30）
- 下午茶時段 15:00～17:00
- 晚餐時段　17:00～21:00（最後點餐時間：20:30）

霧之藏啤酒花園　17:30～21:00（最後點餐時間：20:30）※夏季限定

霧之藏烘焙坊　9:30〜16:00

※其他依設施而異。詳情請於官方網站確認。

霧之藏烘焙坊為週二固定公休
:::


# 吉卜力 
##### [照片](https://www.instagram.com/p/C6qq-DJSrd_/?utm_source=ig_web_copy_link)
## [風之谷巨神兵 ジブリ·ロボット兵のオブジェ](https://maps.app.goo.gl/VJMrwxdqjQbAhfqFA)

## [龍貓公車站](https://maps.app.goo.gl/qaZ9bz9emAimNzvx6)

::: {.callout}
[網站](http://miyazaki.fool.jp/takaharu/?p=1317)
:::

## [Totoro of Futo 富土のトトロ](https://maps.app.goo.gl/6vWh7sS9VMM2YfY17)

# [志布志市役所 本庁](https://maps.app.goo.gl/8uE3PqN7ZAXDfn4k7)

::: {.callout}
志布志市志布志町志布志の志布志 市役所 志布志支所

Shibushi-shi Shibushi-chō Shibushi no Shibushi Shiyakusho Shibushi Shisho
:::